#!/bin/sh
# set user and email address

if [ ! -f ~/.gitconfig ];
then
	echo "~/.gitconfig does not exist, exiting."
	exit
fi

echo "git username:"
read GITUSERNAME
echo "git email:"
read GITEMAIL

# set global confs
git config --global user.name "$GITUSERNAME"
git config --global user.email "$GITEMAIL"
